language: node_js
cache:
  directories:
    - node_modules
node_js:
  - "node"
  - "8"
  - "9"
  - "10"
  - "11"

matrix:
  include:
    - node_js: '6'
      env: NO_LINT=true
    - node_js: '7'
      env: NO_LINT=true

script:
  - if [[ -z "${NO_LINT}" ]]; then npm run lint; fi
  - npm test
